### ISSUE TITLE
Allow negative values when entering resolution/offset in opener dialog

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#119]
Currently, this is not possible when entering numbers manually (text field does not allow single minus sign).

cc @bogovicj

**Comment by bogovicj** [comment]
btw, I wonder about whether negative values for resolution are necessary (I would expect it to act as a flip of the axis about 0).

Negative offsets would be great for sure though.

**Comment by hanslovsky** [comment]
Good point. For now, I will disallow negative resolutions. If they ever become desirable, the fix is as easy as changing `v -> v > 0` to `v -> v != 0` in the code.

**Comment by hanslovsky** [comment]
@bogovicj please run
```
conda update -c hanslovsky paintera
paintera --version
```
Version should be `0.2.4`.
