### ISSUE TITLE
Re-introduce DrawProjectAndIntersectController in javafx-generic-listeners branch

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#12]
Continuing saalfeldlab/bigcat#102
As requested by @axtimwalde

**Comment by hanslovsky** [comment]
Not going to add this.

**Comment by axtimwalde** [comment]
Then leave it open for somebody else to do it?

**Comment by hanslovsky** [comment]
It was my understanding that this class is obsolete with combination of 2D/3D flood fill (better for splitting object) and interpolation between labels. If you feel there is still need for this class please reopen.
