### ISSUE TITLE
Google cloud open dialog does not show any datasets

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#13]
Continuing saalfeldlab/bigcat#105
> The dialog to chose project and bucket comes up, but the choice list for datasets remains empty, no error message or any other information.

**Comment by hanslovsky** [comment]
@axtimwalde You said you had parallelized dataset discovery. Where can I find those changes?

**Comment by axtimwalde** [comment]
in a pull request against your pull request of course

**Comment by axtimwalde** [comment]
@hanslovsky https://github.com/hanslovsky/bigcat/pull/2

**Comment by hanslovsky** [comment]
Thanks @axtimwalde 
Something is really weird with github. I don't get any notifications about PRs/issues in any bigcat repository (base or my fork). Hopefully, this will be better with the new repository.

**Comment by axtimwalde** [comment]
@hanslovsky That's why I rambled about the bureaucracy of this approach ;) BTW can you have a look at what I did there, it was in a bit of a rush and I think that I am not properly calling the onInterrupt handler (which does not seem to change stuff surprisingly).  May be can be removed?

**Comment by hanslovsky** [comment]
With a real master branch, a lot of these issues with missing notifications should go away, hopefully.
I will go through the code and see if it needs any adjustments.
