### ISSUE TITLE
Add script terminal

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#138]

**Comment by hanslovsky** [comment]
On the plane on the way back from the Learnathon I was able to create a first prototype of a JavaFX REPL with the SciJava [`ScriptREPL`](https://github.com/scijava/scijava-common/blob/482c170eefe58078a1affc0e8da5665012501ac1/src/main/java/org/scijava/script/ScriptREPL.java), so hopefully this feature can be added soon. It will require some internal changes and probably  add a SciJava `Context` or `Gateway` to Paintera.
