### ISSUE TITLE
Issues with x11 forwarding

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera#161]
I tried to run paintera with x11 forwarding.
I can start it, load data etc.

However, when I try to maximize or resize the paintera window, it freezes and throws the following error:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

Any ideas?

**Comment by hanslovsky** [comment]
I see these warnings:
```
Nov 14, 2018 7:26:08 AM javafx.scene.LightBase <init>
WARNING: System can't support ConditionalFeature.SCENE3D
```
but I can resize and maximize. The warnings seem to go away if I run paintera like this:
```
paintera -Dprism.forceGPU=true --
```
If there is any way of using vnc instead of x-forwarding, I recommend you use that instead. It is much more responsive.

**Comment by constantinpape** [comment]
I see the same warnings, will check if they go away if I add the `Dprism` option.
I don't know if I have the option to use vnc forwarding, will check with our IT.

**Comment by hanslovsky** [comment]
Some additional info for my system:
Host:
```
▲ ~ xdpyinfo | grep -i version
version number:    11.0
X.Org version: 1.20.3
```
Client:
```
▲ ~ xdpyinfo | grep -i version
version number:    11.0
X.Org version: 1.20.3
```

**Comment by constantinpape** [comment]
This issue is fixed by adding the `Dprism` flag.

**Comment by hanslovsky** [comment]
Thanks for reporting the solution @constantinpape
