### ISSUE TITLE
Data open dialogue: set dataset type to label for label dataset

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera#172]
It would be nice if the type for a dataset that has the attributes `{"painteraData": {"type": "label"}}`
is automatically set to `label` instead of `raw` in the data open dialogue.

**Comment by hanslovsky** [comment]
The logic should probably be:
 - is paintera dataset?
    - set to`label` if `"type": "label" else `raw`
 - else
    - set to `label` if `LabelMultisetType` or `UINT64` else `raw.

**Comment by hanslovsky** [comment]
@constantinpape this is fixed in 0.13.0 and will be released to conda soon!

**Comment by hanslovsky** [comment]
Soon = now:
```
conda update -c hanslovsky paintera
```
