### ISSUE TITLE
Update coordinate display on keyboard navigation

### ISSUE THREAD

**Issue by aschampion** [saalfeldlab/paintera#204]
Otherwise the coordinates will only update on mouse move. When trying to scroll through Z to a particular section, this can be cumbersome.

**Comment by hanslovsky** [comment]
Relevant classes:
https://github.com/saalfeldlab/paintera/blob/dfb2dad80c5a08bcff68d1238e0ed1f82924e51b/src/main/java/org/janelia/saalfeldlab/paintera/control/OrthoViewCoordinateDisplayListener.java
https://github.com/saalfeldlab/paintera/blob/dfb2dad80c5a08bcff68d1238e0ed1f82924e51b/src/main/java/org/janelia/saalfeldlab/paintera/control/OrthogonalViewsValueDisplayListener.java

Would you want to make a PR?

**Comment by aschampion** [comment]
> Would you want to make a PR?

Sure, I'll get around to it.

**Comment by hanslovsky** [comment]
Thanks, much appreciated!
