### ISSUE TITLE
Starting to paint (SPACE + left click) before canvas has finished painting at full resolution hangs GUI

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#210]
Observed on Ubuntu 18.04 (could be a Gnome issue because Gnome has issues).  Will try to deliver an exception trail next time it happens...

**Comment by cmhulbert** [comment]
@axtimwalde this is related to one of the first things I worked on with Paintera; It should block the UI from painting now (swirling cursor, and disable click). If you haven't seen this issue recently (the past year or so) I'm inclined to mark it complete

**Comment by axtimwalde** [comment]
Yes, haven't seen this recently.
