### ISSUE TITLE
Cannot change interpolation to NLinear for raw data sources

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#214]
Interpolation is always set to `NearestNeighbor` even for raw data sources. It's supposed to switch to `NLinear` on pressing `I`, but the interpolation property in `SourceState` remains the same so the change doesn't occur.

**Comment by hanslovsky** [comment]
I wonder when that bug was introduced, maybe when restructuring the handlers.

**Comment by hanslovsky** [comment]
This seems to work now, can I close this @igorpisarev?

**Comment by igorpisarev** [comment]
Yes, it's been fixed there, closing now
