### ISSUE TITLE
Restrict width of status bar (bottom)

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#217]
The status bar prints, amongst other things, the voxel value under the cursor. For large multi-sets or many channels, this can be a very long string. The width of the status bar is (or seems to be) unconstrained, which leads to weird resizing and rendering artifacts. The fix should be easy: Restrict the width of the status bar (or its contents).

The easiest way to re-produce is with either a dataset with many channels (e.g. 12 channel affinity predictions) or downsampled label-multisets from high-variance label data and relatively small Paintera window size.

It is probably sufficient to restrict the width of the [status bar](https://github.com/saalfeldlab/paintera/blob/f5c43f51ff7360651bdf412eff06a79b05b87a88/src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java#L65), and possibly its children.

**Comment by hanslovsky** [comment]
cc @igorpisarev

**Comment by igorpisarev** [comment]
Tried `statusBar.setMaxWidth()` but it didn't prevent the contents from growing past the size of the parent, so it seems that for some reason it doesn't have any effect.
Putting this constraint on `valueStatus` label works, but the constraint is not dynamic so it may still overshoot when the window is small while being unnecessarily short when maximized.

I will try to experiment more with `HBox.setHgrow()` and setting preferred component sizes.

**Comment by hanslovsky** [comment]
Thanks for looking into this @igorpisarev 
I might have set minimum width for some of the children elements, which could also be an issue here.
