### ISSUE TITLE
2D fill captures mouse and freezes Paintera on Ubuntu 18.04 GNOME

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#230]
sometimes, not always, but frequently enough that it hurts.  This could of course be an issue with the Gnome shell which is, as we all know, a giant piece of ...

**Comment by hanslovsky** [comment]
Do you know if it happens at a specific sequence of interactions or at random?

**Comment by hanslovsky** [comment]
@axtimwalde is that because the dialog pops up behind the Paintera main window and blocks controls? Or is this unrelated?

**Comment by axtimwalde** [comment]
May be.  Closing because hasn't happened recently.  Thanks for looking at this.
