### ISSUE TITLE
Save-quit-load of a project does not preserve mesh rendering Ok

### ISSUE THREAD

**Issue by pgunn** [saalfeldlab/paintera#232]
Right now if you load raw hdf5 datafiles, you can tell paintera that it should generate meshes on-the-fly in the dialogues that pop up. If you save a project made that way, quit, and reload it, your "ok" is not preserved and Paintera will not generate meshes in that project any more.

**Comment by hanslovsky** [comment]
That is an annoyance, indeed. I am currently on the road but I might be able to have a look on it next Tuesday.

**Comment by hanslovsky** [comment]
The meta information (dimensions, block size) is not stored with the lookup (index) from label id to containing blocks and, as a result, the deserialized lookup is not valid and cannot generate the blocks. I will look into how to fix this issue.

**Comment by hanslovsky** [comment]
Wrong annotations in [`LabelBlockLookupAllBlocks`](https://github.com/saalfeldlab/paintera/blob/f5ae6008def33ddf8be9c30971f83a4b41f6b08f/src/main/java/org/janelia/saalfeldlab/util/grids/LabelBlockLookupAllBlocks.java#L23-L27) and wrong `@Target` in [`LabelBlockLookup`](https://github.com/saalfeldlab/label-utilities/blob/69fb2dd3085b4cc0b52324995d896cef65b323fb/src/main/kotlin/org/janelia/saalfeldlab/labels/blocks/LabelBlockLookup.kt#L30-L33).

I fixed both things locally and it seemed to work. Will have to update and release label-utilities before I can fix this in Paintera.

**Comment by hanslovsky** [comment]
@pgunn I found the cause and once I can confirm that the changes in saalfeldlab/label-utilities#5 do not affect current behavior, I will release label-utilities and fix the annotation issue in Paintera.

**Comment by pgunn** [comment]
Rockin' - LMK when there's a new conda release available.

**Comment by hanslovsky** [comment]
Probably not tonight (on Europe time right now), but tomorrow is a possibility.

**Comment by hanslovsky** [comment]
Paintera 0.13.0 is now available on conda:
```
conda update -c hanslovsky paintera
```
Let me know if you have any issues.
