### ISSUE TITLE
Have paintera and paintera-conversion-tool indicate when (during launch) they're waiting on maven

### ISSUE THREAD

**Issue by pgunn** [saalfeldlab/paintera#233]
Right now, there's no indication that maven is finishing the install when these tools launch for the first time. It'd be good to tell the user that there's some mavening underway.

**Comment by hanslovsky** [comment]
This should be addressed upstream in scijava/jgo#40

**Comment by hanslovsky** [comment]
Will close this as soon as scijava/jgo#48 is merged

**Comment by pgunn** [comment]
Awesome! Thanks

**Comment by cmhulbert** [comment]
Closed by https://github.com/scijava/jgo/pull/48
