### ISSUE TITLE
Display scalebar in pantera

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera#238]
Bigdataviewer supports the option for a dynamic scalebar to be displayed based on the resolution values.
Is it possible to show this in paintera as well?

**Comment by hanslovsky** [comment]
This would certainly possible. Paintera does not know about physical units at the time, or rather, by convention, the "global coordinates" are in units of nanometer by convention (not explicitly stated) and that information could be used to create a scale bar overlay.

PRs always welcome.
