### ISSUE TITLE
Label rendering slows to a halt when many objects are selected

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#264]
The culprit is most likely this inefficient contains test

https://github.com/saalfeldlab/paintera/blob/e95884e4881acd4b675e9a9b45a2f9123ae2f1ca/src/main/java/org/janelia/saalfeldlab/paintera/stream/AbstractHighlightingARGBStream.java#L110-L130

which must be replaced by an efficient contains test.  Working on it...

**Comment by axtimwalde** [comment]
WIP https://github.com/saalfeldlab/paintera/tree/label-render-speed

**Comment by hanslovsky** [comment]
Closed in #269
