### ISSUE TITLE
Update to Java 11 compatible imglib2-cache

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#280]
After https://github.com/imglib/imglib2-cache/pull/11 this should be possible.

Benefits:
 - Java 11
 - OpenJFX through maven
 - Distribute entirely through conda, including openjdk 11 dependency

It may require some work, though.

**Comment by cmhulbert** [comment]
@ctrueden as you say, Paintera now is built with Java 11, and we use the most recent version of imglib2-cache; I believe the effort this issues was intended to track is completed, I'll close it out.
