### ISSUE TITLE
2D flood-filling needs to be non-blocking and cancelable

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#303]
I managed to completely freeze the application by 2D flood-filling inside the painted boundaries of an object. It might be that the boundaries I painted were not continuous (although they appeared so), and it started filling the entire canvas.

2D flood-fill needs to be run in a background thread in the same way as 3D flood-fill. The confirmation dialog as suggested in #302 would probably be an overkill for 2D flood-filling, but instead it could check if the area is enclosed or not, and don't do anything if it reaches the source's boundaries.

**Comment by cmhulbert** [comment]
[Release 0.32.0 ](https://github.com/saalfeldlab/paintera/tree/paintera-0.32.0)makes 2D flood fill non-blocking on the UI thread, and cancelable (via ESC or toolbar)
