### ISSUE TITLE
Ortho slices out of view

### ISSUE THREAD

**Issue by sheridana** [saalfeldlab/paintera#307]
When the data source offset is not set to (0,0,0) the 3d ortho slices are not centered. This is problematic for working with datasets extracted from larger regions which tend to have very large offsets (in world coords) - the user needs to find the planes and manually center them. An immediate fix on the users end is to just set the raw offset to (0,0,0) and calculate the new offset for the labels when loading the datasets. However, it would be preferable for the ortho slices to automatically be centered regardless of the offset.

**Comment by hanslovsky** [comment]
Thanks for raising this @sheridana

**Comment by hanslovsky** [comment]
How to reproduce: In an empty project, open an arbitrary dataset, e.g. any remi dataset. In the opener dialog, set the offset to something really large, e.g. `1_000_000, 1_000_000, 1_000_000` and good luck finding the ortho views in the 3D viewer. Hint: Setting the 3D viewer to background and zooming out very far in the 2D viewers helps.
