### ISSUE TITLE
Paintera does not open HDF5 sources

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#31]
Trying to open a raw single scale dataset from HDF5 does not create a source entry and does not show anything in the viewers.  The same dataset after copy-converting to N5 with n5-copy works just fine.

**Comment by hanslovsky** [comment]
Fixed in 027ada4faa308c3d1db85a14fdfbe4f7ae700915
Will be available in master upon merge of [render-thresholded](https://github.com/saalfeldlab/paintera/tree/render-thresholded) branch
