### ISSUE TITLE
Can't paint on the first/last frame of the volume

### ISSUE THREAD

**Issue by wangyuhan01** [saalfeldlab/paintera#342]
Not sure if this is an issue on my end or a general issue, but I was having trouble painting on the very first/last frame of the image volume, when I tried to do that,  the painting appeared on the second frame. 

On a separate note,  the new interface looks AWESOME! Thanks for the great work!

**Comment by hanslovsky** [comment]
Can you share the data that you are working on? I tried on one of the CREMI datasets and cannot reproduce there, but it may be only for certain resolutions.

> On a separate note, the new interface looks AWESOME! Thanks for the great work!

Thanks, much appreciated :fireworks:

**Comment by wangyuhan01** [comment]
Due to the file size limit, I have deposited the file to the following link: 
https://www.dropbox.com/s/k4rl81by90qy5vn/2019_r3_13_1390_1178.n5.zip?dl=0
The file path in json will need to be modified. Thanks!

**Comment by hanslovsky** [comment]
@wangyuhan01 I was able to confirm that behavior with the data that you provided.

**Comment by hanslovsky** [comment]
I also noticed that the label data is "smaller" even though both datasets have the same transform
```bash
$ grep '"transform"' -A 13 attributes.json
              "transform": [
                0.23,
                0.0,
                0.0,
                0.0,
                0.0,
                0.23,
                0.0,
                0.0,
                0.0,
                0.0,
                0.42,
                0.0
              ]
--
                "transform": [
                  0.23,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  0.23,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  0.42,
                  0.0
                ]
``` 
and dimensions
```shell
$ jq '.dimensions' t0/channel0/data/s0/attributes.json labels/data/s0/attributes.json
[
  1920,
  1920,
  213
]
[
  1920,
  1920,
  213
]
```


Note that, hopefully soon, datasets can be relative to a project directory without having to rename the paths in the project file: https://github.com/saalfeldlab/paintera/pull/343

**Comment by igorpisarev** [comment]
Maybe this is a side effect of #220 where I changed the half-pixel offsets in the mask transformations, although I thought that I got them correctly in that PR.

**Comment by wangyuhan01** [comment]
Thank you for looking into this. If it helps, the label dataset was created in paintera through Ctrl+Shift+N and I only defined the pixel size (0.23, 0.23, 0.42) and used the default image dimension.

**Comment by hanslovsky** [comment]
@igorpisarev I don't think it is that because it happens on both sides of the data in each dimensions. If the offset was wrong, we should see it only on one side and an overhang on the other side instead, no?

**Comment by igorpisarev** [comment]
Ah, yes, then it's probably something else. I haven't looked into it, but this was just my hypothesis that if the offsets are slightly off, it would round up the 0.5px and treat the last slice as being outside.

**Comment by axtimwalde** [comment]
Works now, painting logic has changed and fixed this.
