### ISSUE TITLE
Jitter during navigation

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#345]
There is occasional slight jitter when navigating in the 2D viewer, observed on @axtimwalde's laptop and can also be seen in a screencast by @hanslovsky. Basically the viewer jitters back for a short period of time, so it looks like an older frame is displayed between the two newer frames.

I've pushed some experimental code to the branch https://github.com/saalfeldlab/paintera/tree/rendered-frame-order to test the assumption that an outdated frame might come in after a newer one has been received (and to ignore these outdated frames), but it turns out that it never happens, so there must be something else that causes the jitter.

It seems that the jitter also occurs with only one screen scale value (when there is no switching between the screen scales), and it's stronger when the screen scale value is lower, so that the frames are produced more quickly. Possibly there is some kind of race condition in either switching between the render buffers or updating the viewer transform.

**Comment by hanslovsky** [comment]
A side note that may or may not be relevant: I only observed this (so far) when doing the screen cast, i.e. performance was inhibited by the screen recording, but I may just have not been aware of it before.

**Comment by axtimwalde** [comment]
Haven't seen this in ages, assume that changes in the rendering code have either fixed this or computers got better.
