### ISSUE TITLE
Add assignments to mark segments as complete (and hide them).

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#35]
Also add keyboard shortcut to hide or show completed segments.

**Comment by hanslovsky** [comment]
Added this to 0.1.0 milestone.

**Comment by hanslovsky** [comment]
Will work on this on this branch:
https://github.com/saalfeldlab/paintera/tree/mark-segments-complete

**Comment by hanslovsky** [comment]
First commit (dceaf5960990274759d6cf4b35eddffa65ba3152) adds ARGBStream support for locked segments.
TODO:
 - disable split/merge when locked (what to do about paint? Maybe disallow paint when locked segment is selected and disallow painting into locked segments)
 - add UI controls for locked alpha or simple switch visible/non visible (probably prefer the latter)

**Comment by hanslovsky** [comment]
@axtimwalde This might be good enough for what you need as is already. The state of locked segments is not being persisted yet but that is on the roadmap. Will merge into master once the two remaining points on the list are crossed off.

**Comment by axtimwalde** [comment]
@hanslovsky Thanks! As discussed offline, I do not currently think that `locking' is high priority, albeit interesting and useful. What we need though is tagging stuff as 'processed' so one doesn't loose track.  During proofreading in CREMI e.g., that means tagging neurons that have seen a lot of work and cannot be easily completed further.  At a later time, one then merges additional fragment to these 'complete' neurons which is kindn of the opposite of locking :).

**Comment by hanslovsky** [comment]
I do think that anything that is marked as processed should also be locked to avoid accidential changes. Things can always be unlocked via single button (`L`), so it's always going to be possible to modify those later on.

**Comment by hanslovsky** [comment]
@axtimwalde I will postpone locking the marked segments to post 0.1.0 (will create a separate issue). The marked segments are stored in the project. Should they also be stored with the dataset (i.e. global storage vs user space only)? If not, the feature branch is ready for a merge.
