### ISSUE TITLE
Visualise mesh vertices

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/paintera#356]
@hanslovsky 
Is it possible to generate an image like this?
<img width="698" alt="image" src="https://user-images.githubusercontent.com/2157566/70326508-fec65c00-1834-11ea-9a29-c38deed310cb.png">
We would like to see the mesh vertices as in above image.

**Comment by hanslovsky** [comment]
Try changing the draw mode in the `Mesh Settings` tab of your label source to `LINE`. For line mode, it is probably best to set the cull face to `NONE`:

![Screenshot_20191206_105116](https://user-images.githubusercontent.com/1086317/70335959-56a19a80-1816-11ea-9149-c9193cd53909.png)

**Comment by hanslovsky** [comment]
@tischi did this work for you?

**Comment by tischi** [comment]
it worked for us.
