### ISSUE TITLE
Bugs in display status of ConnectomicsLabelState

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera#370]
It seems that a few bugs sneaked in when the display status of `LabelSourceState` was ported to `ConnectomicsLabelState`:
* Source name is not displayed
* When no label is selected, the colored square still displays the last selected color (or black if the application was just started and no label was selected yet)
* The progress indicator is not displayed for 3D fill. There is also no way of cancelling 3D fill (ESC doesn't work either now)

**Comment by igorpisarev** [comment]
Just wanted to bring this issue to attention before we make a release. Since I originally implemented the display status for label sources, I can look into porting the rest of the logic to fix the described bugs.

**Comment by hanslovsky** [comment]
Thanks @igorpisarev
