### ISSUE TITLE
Improve handling of dataset opening errors when opening a project

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#375]
Currently, when Paintera cannot open a dataset when deserializing a project, Paintera just crashes. Instead, we should implement a more graceful handling scheme. If a dataset cannot be deserialized, present the user with the following options:
 1. Remove the dataset from the project (this may require additional checks for dependent datasets that maybe should be removed, as well).
 2. Ignore the failing dataset but store its information, so it can be serialized and the information is not lost when the project is overwritten (this may require additional checks for dependent datasets that maybe should be removed, as well). This can be achieved with a `UnableToDeserializeSourceState` class, that just holds all the entries from the `JsonObject` that describes this dataset in the Paintera project, and serializes those verbatim whenever the project is saved. Additionally, it should always be invisible.
 3. Exit Paintera gracefully, so the user can modify the project attributes offline.

**Comment by cmhulbert** [comment]
When a source is not detected, the following alert will now show up, giving the user the. choice to:
1. specify the correct path to the container
2. remove the source
3. quit

<img width="531" alt="image" src="https://github.com/user-attachments/assets/412801e0-e3b4-45a2-901b-fbff56020af7">
