### ISSUE TITLE
3D viewer unresponsive with moderately large objects

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#4]
Continuing saalfeldlab/bigcat#49
> With any object that has a few thousand mesh blocks, the entire applications becomes unusably slow. At this level, single triangles are still visible for the entire object, i.e. the number of triangles is not expected to be too large for the graphics card. My graphics card is a Titan X with 32GB, this should work. If this is a limit of JavaFX 3D we should run away from it... fast!

**Comment by hanslovsky** [comment]
@axtimwalde Are you still experiencing this?

**Comment by axtimwalde** [comment]
Nope :)
