### ISSUE TITLE
Add UI controls to enable/disable rotations in 2d views

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera#42]

**Comment by axtimwalde** [comment]
If that means adding the keyboard rotation controls of BigCat, triple thumbs up.  Including chosing the axis of rotation with the x,y,z keys.  Always around the selected axis intersecting the view panel center.  <- rotate ccw, -> rotate cw 1degree. Ctrl 0.1 degrees, Shift 10 degrees.

**Comment by axtimwalde** [comment]
From here:

https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/BehaviourTransformEventHandler3D.java

**Comment by hanslovsky** [comment]
This issue is for a adding a switch to entirely disable rotations.
The behavior you describe is already available with steps of 5° and 45°

**Comment by hanslovsky** [comment]
Fixed in 1280fee6c746065e1b062b6185fc145cfffc8395
