### ISSUE TITLE
Shape Interpolation not working properly when selecting existing label

### ISSUE THREAD

**Issue by cmhulbert** [saalfeldlab/paintera#481]
reported by @axtimwalde 

Inconsistent shape interpolation behavior when selecting existing labels, or using floodfill during shape interpoloation. Sometimes the label slice is not selected, and the key slice is not added for interpolation.

**Comment by cmhulbert** [comment]
@axtimwalde this should have been resolved in the most recent release (0.34.0) Feel free to close this if so.

**Comment by axtimwalde** [comment]
Thanks!
