### ISSUE TITLE
Keyboard navigation with Cursor right broken

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#76]
Keyboard navigation as described in https://github.com/saalfeldlab/paintera/issues/42 is still not usable because Cursor right changes the focus (or something).  Only one action is executed, then no navigation is possible until the focus is re-captured (using the mouse).  Also, change to 0.1, 1, and 10 degrees as in BigCAT.

**Comment by hanslovsky** [comment]
Focus traversal issues can be resolved by adding call to `Event.consume()` to [`EventFX.EventFXWithConsumer.actOn`](https://github.com/saalfeldlab/paintera/blob/1801afc4ad6567982fba832964d13345ca1d7aca/src/main/java/org/janelia/saalfeldlab/fx/event/EventFX.java#L117). That should not change existing behavior (and if it does, that was wrong in the first place). I will use it a little more to see if I observe any changed behaviors.

**Comment by hanslovsky** [comment]
Unforunately, this breaks the painting controls, most likely because `MouseClickFX.onRelease` runs on any release (without any checks/filters). I will try replacing `event -> true` with `event -> isEvent`.

**Comment by hanslovsky** [comment]
That seems to do the trick.

**Comment by hanslovsky** [comment]
Now we can also uncomment [click paint handlers](https://github.com/saalfeldlab/paintera/blob/master/src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java#L128-L130)
